### ISSUE TITLE
Roadmap / Definition of Done

### ISSUE THREAD

**Issue by AirOne01** [AirOne01/proxyster#16]
# What should be done

## Architecture/refractor
- [ ] Client-Server architecture
  - [x] Client can run on its own
    - [x] #10 
  - [ ] Proper protocol
- [ ] Actual futures (async)

## Fail-safety
- [ ] [TBD] Full fail-safety handling
- [ ] Logging
  - [x] #14 
  - [ ] Log everything
  - [ ] Proper logging levels (and verbose)

## ("secondary") Before v1
- [ ] Privacy-by-default
  - [ ] Scraping proxies through proxies
  - [ ] Scraping proxies through TOR
- [ ] Documentation

## ("secondary") CI/CD
- [ ] CI
  - [ ] Tests (lol)
  - [ ] Coverage
- [ ] [TBD] CD
